### Criar usuário

POST https://node-flutter-krtl.onrender.com/users
Content-Type: application/json

{
    "name": "Gabriela",
    "email": "iansilva@criancaa.com"
}

### Listar usuários

GET https://node-flutter-krtl.onrender.com/users

### Criar cliente para um usuário

POST https://node-flutter-krtl.onrender.com/users/a93ed86c-966b-4119-8f40-25a882215476/clients
Content-Type: application/json

{
    "name": "crianda2",
    "email": "crianasa@gmail.com",
    "data": {
        "info": "ao lado do pet shop"
    }
}

### Listar clientes de um usuário

GET https://node-flutter-krtl.onrender.com/users/a93ed86c-966b-4119-8f40-25a882215476/clients

###

DELETE https://node-flutter-krtl.onrender.com/users/6c9a1d6a-4190-42f4-b648-49a4a07d0a91

###

DELETE https://node-flutter-krtl.onrender.com/users/6c9a1d6a-4190-42f4-b648-49a4a07d0a91/clients/3